- Read sheet "Australia by Residence" from Australia.xlsx
- Ignore the first 20 rows.
- List all Column and Row indexes(Print their names)

Dataset Analysis
- Describe the dataset
- Use values and index attributes on both Row and Column Indexes
- Check Shape, Datatypes and other attributes
- Observe the datatype of each columns' data
  

Drop
- Delete all Data where the Type = "Emmigrants" or Type is not "Immigrants" (Row Deletion)
- Find columns for which more than 50% data is missing and drop them (Column Deletion)
- Drop Unnessary Columns: Type, Coverage, Area, Reg, Dev (Column deletion)
    Your columns should now look like "OdName,AreaName,RegName,DevName,1980 ... 2008"

Rename
- Rename columns :OdName -> Country; RegName -> Region
- Convert Column Names with Int type to Strings to avoid index errors with string indexing "1980, 1981 etc." => " '1980', '1981' ... " (Use rename)
- Save the dataset to a new file AustraliaFiltered.csv

Head Tail Sort
- Find Total number of immigrants for all years, and create a new column Total in data Frame
- Sort Data by the new column Total and analyze the fist few rows. (get first few rows using head)
    - find something weird in the dataset ? Delete that row 'world'
- Analyze last few rows also in the sorted result (Don't sort inplace)

- Check if these have all unique values or not:
    - countries
    - continents
    - country continent pairs


- Find countries for which no of immigrants for all years is 0
- Find count of above countries
- Find countries for which no of immigrants is 0 for any year

In [1]:
import pandas as pd

In [13]:
df1 = pd.read_excel(r'C:\Users\Dell\Desktop\weekday2019_08_06\Assignments\Australia.xlsx',sheet_name = 'Australia by Residence',skiprows = 20)

In [14]:
dfObj = pd.DataFrame(df1, columns= ['Type','Coverage','OdName','AreaName','RegName','DevName'])

In [15]:
print(df1.describe(include = 'all'))

             Type Coverage OdName        AREA AreaName          REG  \
count         448      448    448  448.000000      448   448.000000
unique          2        1    224         NaN        7          NaN
top     Emigrants     Both  Benin         NaN   Africa          NaN
freq          224      448      2         NaN      112          NaN
mean          NaN      NaN    NaN  912.955357      NaN  1208.040179
std           NaN      NaN    NaN   15.019682      NaN  1109.669573
min           NaN      NaN    NaN  903.000000      NaN   905.000000
25%           NaN      NaN    NaN  903.750000      NaN   914.000000
50%           NaN      NaN    NaN  908.000000      NaN   922.000000
75%           NaN      NaN    NaN  909.000000      NaN   926.000000
max           NaN      NaN    NaN  999.000000      NaN  5501.000000

          RegName         DEV             DevName           1980  ...  \
count         448  448.000000                 448     448.000000  ...
unique         23         NaN                   3            NaN  ...
top     Caribbean         NaN  Developing regions            NaN  ...
freq           46         NaN                 344            NaN  ...
mean          NaN  902.642857                 NaN    1228.348214  ...
std           NaN    9.165500                 NaN   10145.734028  ...
min           NaN  901.000000                 NaN       0.000000  ...
25%           NaN  902.000000                 NaN       0.000000  ...
50%           NaN  902.000000                 NaN      10.000000  ...
75%           NaN  902.000000                 NaN     130.000000  ...
max           NaN  999.000000                 NaN  184290.000000  ...

                 2004           2005           2006           2007  \
count      448.000000     448.000000     448.000000     448.000000
unique            NaN            NaN            NaN            NaN
top               NaN            NaN            NaN            NaN
freq              NaN            NaN            NaN            NaN
mean      2514.241071    2545.357143    2709.866071    3023.348214
std      19834.528214   20203.441660   21786.641444   24542.748186
min          0.000000       0.000000       0.000000       0.000000
25%         10.000000      10.000000      10.000000      10.000000
50%         50.000000      50.000000      60.000000      70.000000
75%        400.000000     410.000000     455.000000     480.000000
max     350990.000000  363470.000000  402210.000000  460650.000000

                 2008  2009  2010  2011  2012  2013
count      448.000000   448   448   448   448   448
unique            NaN     1     1     1     1     1
top               NaN    ..    ..    ..    ..    ..
freq              NaN   448   448   448   448   448
mean      3376.116071   NaN   NaN   NaN   NaN   NaN
std      27950.462893   NaN   NaN   NaN   NaN   NaN
min          0.000000   NaN   NaN   NaN   NaN   NaN
25%         10.000000   NaN   NaN   NaN   NaN   NaN
50%         75.000000   NaN   NaN   NaN   NaN   NaN
75%        512.500000   NaN   NaN   NaN   NaN   NaN
max     535970.000000   NaN   NaN   NaN   NaN   NaN

[11 rows x 43 columns]

In [18]:
print(df1.columns)
print(df1.shape)

Index([    'Type', 'Coverage',   'OdName',     'AREA', 'AreaName',      'REG',
        'RegName',      'DEV',  'DevName',       1980,       1981,       1982,
             1983,       1984,       1985,       1986,       1987,       1988,
             1989,       1990,       1991,       1992,       1993,       1994,
             1995,       1996,       1997,       1998,       1999,       2000,
             2001,       2002,       2003,       2004,       2005,       2006,
             2007,       2008,       2009,       2010,       2011,       2012,
             2013],
      dtype='object')
(448, 43)

In [17]:
print(df1.dtypes)

Type        object
Coverage    object
OdName      object
AREA         int64
AreaName    object
REG          int64
RegName     object
DEV          int64
DevName     object
1980         int64
1981         int64
1982         int64
1983         int64
1984         int64
1985         int64
1986         int64
1987         int64
1988         int64
1989         int64
1990         int64
1991         int64
1992         int64
1993         int64
1994         int64
1995         int64
1996         int64
1997         int64
1998         int64
1999         int64
2000         int64
2001         int64
2002         int64
2003         int64
2004         int64
2005         int64
2006         int64
2007         int64
2008         int64
2009        object
2010        object
2011        object
2012        object
2013        object
dtype: object

In [22]:
print(df1.columns.values[2])
print(df1.index.values[2])

OdName
2

In [33]:
df1 =df1.drop(df1[df1.Type != 'Immigrants'].index)

In [34]:
thresh = len(df1) * 0.5
print(df1.dropna(thresh = thresh, axis =1,inplace = True))

None

In [38]:
#Type, Coverage, Area, Reg, Dev
df1.drop(['Type','Coverage','AREA','REG','DEV'],axis=1,inplace = True)

In [39]:
df1 = df1.rename(columns = {"OdName":"Country","RegName":"Region"})
print(df1.columns)

Index([ 'Country', 'AreaName',   'Region',  'DevName',       1980,       1981,
             1982,       1983,       1984,       1985,       1986,       1987,
             1988,       1989,       1990,       1991,       1992,       1993,
             1994,       1995,       1996,       1997,       1998,       1999,
             2000,       2001,       2002,       2003,       2004,       2005,
             2006,       2007,       2008,       2009,       2010,       2011,
             2012,       2013],
      dtype='object')

In [41]:
df1.columns.map(type)

Index([<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>],
      dtype='object')

In [43]:
df1.rename(columns = lambda x: str(x), inplace=True)
#df1.columns = df1.columns.astype(str)-- this also can work
df1.columns.map(type)

Index([<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>,
       <class 'str'>, <class 'str'>],
      dtype='object')

In [44]:
df1.to_csv('Australia_filtered.csv')

In [47]:
total = df1.count(axis='columns')
df1["Total"] = total
print(df1.columns)

Index(['Country', 'AreaName', 'Region', 'DevName', '1980', '1981', '1982',
       '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', 'Total'],
      dtype='object')

In [48]:
df1

,Country,AreaName,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
224,Afghanistan,Asia,Southern Asia,Developing regions,10,20,30,30,70,100,...,110,180,140,560,..,..,..,..,..,39
225,Albania,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,130,110,110,140,..,..,..,..,..,39
226,Algeria,Africa,Northern Africa,Developing regions,10,50,30,10,20,20,...,50,30,30,60,..,..,..,..,..,39
227,American Samoa,Oceania,Polynesia,Developing regions,0,0,0,0,0,20,...,0,0,0,10,..,..,..,..,..,39
228,Andorra,Europe,Southern Europe,Developed regions,0,0,10,0,0,0,...,10,0,10,10,..,..,..,..,..,39
229,Angola,Africa,Middle Africa,Developing regions,0,0,0,10,0,0,...,10,20,30,20,..,..,..,..,..,39
230,Anguilla,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,..,..,..,..,..,39
231,Antigua and Barbuda,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,10,10,0,0,..,..,..,..,..,39
232,Argentina,Latin America and the Caribbean,South America,Developing regions,570,640,850,520,400,540,...,450,430,460,490,..,..,..,..,..,39
233,Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,40,20,40,60,..,..,..,..,..,39
234,Aruba,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,..,..,..,..,..,39
235,Australia,Oceania,Australia and New Zealand,Developed regions,280,180,170,150,120,150,...,700,140,220,780,..,..,..,..,..,39
236,Austria,Europe,Western Europe,Developed regions,4100,3510,5120,1670,1040,970,...,650,790,570,600,..,..,..,..,..,39
237,Azerbaijan,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,40,30,50,30,..,..,..,..,..,39
238,Bahamas,Latin America and the Caribbean,Caribbean,Developing regions,10,20,0,20,20,20,...,20,30,20,20,..,..,..,..,..,39
239,Bahrain,Asia,Western Asia,Developing regions,70,100,80,160,160,140,...,460,490,240,220,..,..,..,..,..,39
240,Bangladesh,Asia,Southern Asia,Developing regions,170,180,220,140,170,220,...,1860,2570,3680,3160,..,..,..,..,..,39
241,Barbados,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,10,10,20,...,20,10,10,10,..,..,..,..,..,39
242,Belarus,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,70,50,60,60,..,..,..,..,..,39
243,Belgium,Europe,Western Europe,Developed regions,230,270,400,280,260,270,...,410,480,530,560,..,..,..,..,..,39
244,Belize,Latin America and the Caribbean,Central America,Developing regions,0,0,0,0,0,0,...,0,10,0,0,..,..,..,..,..,39
245,Benin,Africa,Western Africa,Developing regions,0,0,0,0,0,0,...,0,0,90,210,..,..,..,..,..,39
246,Bermuda,Northern America,Northern America,Developed regions,20,20,30,30,20,20,...,20,50,30,50,..,..,..,..,..,39
247,Bhutan,Asia,Southern Asia,Developing regions,0,0,10,10,0,10,...,70,90,100,150,..,..,..,..,..,39
248,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,20,30,20,30,30,30,...,40,50,50,50,..,..,..,..,..,39
249,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,240,250,300,320,..,..,..,..,..,39
250,Botswana,Africa,Southern Africa,Developing regions,20,40,40,80,40,50,...,260,200,230,260,..,..,..,..,..,39
251,Brazil,Latin America and the Caribbean,South America,Developing regions,270,220,290,230,310,320,...,2050,2910,3370,4010,..,..,..,..,..,39
252,British Virgin Islands,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,10,...,0,0,10,20,..,..,..,..,..,39
253,Brunei Darussalam,Asia,South-Eastern Asia,Developing regions,80,100,140,150,170,200,...,630,750,630,820,..,..,..,..,..,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,The former Yugoslav Republic of Macedonia,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,510,610,650,660,..,..,..,..,..,39
419,Timor-Leste,Asia,South-Eastern Asia,Developing regions,0,0,0,0,0,0,...,170,970,450,370,..,..,..,..,..,39
420,Togo,Africa,Western Africa,Developing regions,0,0,0,0,0,0,...,0,10,0,30,..,..,..,..,..,39
421,Tokelau,Oceania,Polynesia,Developing regions,0,0,0,0,0,0,...,10,30,10,20,..,..,..,..,..,39
422,Tonga,Oceania,Polynesia,Developing regions,130,290,300,200,250,250,...,330,350,390,640,..,..,..,..,..,39
423,Trinidad and Tobago,Latin America and the Caribbean,Caribbean,Developing regions,20,30,30,10,10,20,...,40,60,30,60,..,..,..,..,..,39
424,Tunisia,Africa,Northern Africa,Developing regions,0,0,0,0,0,0,...,0,30,20,10,..,..,..,..,..,39
425,Turkey,Asia,Western Asia,Developing regions,1500,1390,870,930,1320,1690,...,1720,1690,1860,2080,..,..,..,..,..,39
426,Turkmenistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,0,0,0,0,..,..,..,..,..,39
427,Turks and Caicos Islands,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,..,..,..,..,..,39
428,Tuvalu,Oceania,Polynesia,Developing regions,10,30,30,40,20,30,...,20,20,20,10,..,..,..,..,..,39
429,Uganda,Africa,Eastern Africa,Developing regions,40,30,30,20,20,30,...,670,930,820,460,..,..,..,..,..,39
430,Ukraine,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,420,360,410,420,..,..,..,..,..,39
431,United Arab Emirates,Asia,Western Asia,Developing regions,40,70,80,130,140,140,...,3660,4680,3760,4160,..,..,..,..,..,39
432,United Kingdom of Great Britain and Northern I...,Europe,Northern Europe,Developed regions,43540,57050,51730,31660,25150,27630,...,53300,57250,61490,65160,..,..,..,..,..,39
433,United Republic of Tanzania,Africa,Eastern Africa,Developing regions,70,120,100,90,110,120,...,930,890,1280,760,..,..,..,..,..,39
434,United States of America,Northern America,Northern America,Developed regions,10470,12080,12490,11110,11840,12480,...,18490,17320,19260,20860,..,..,..,..,..,39
435,United States Virgin Islands,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,..,..,..,..,..,39
436,Uruguay,Latin America and the Caribbean,South America,Developing regions,310,280,220,170,390,280,...,110,90,90,100,..,..,..,..,..,39
437,Uzbekistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,70,60,80,110,..,..,..,..,..,39
438,Vanuatu,Oceania,Melanesia,Developing regions,150,140,170,140,170,170,...,350,390,400,400,..,..,..,..,..,39
439,Venezuela (Bolivarian Republic of),Latin America and the Caribbean,South America,Developing regions,90,70,70,80,60,80,...,180,160,160,250,..,..,..,..,..,39
440,Viet Nam,Asia,South-Eastern Asia,Developing regions,130,70,200,920,2860,2140,...,5110,6610,8310,11210,..,..,..,..,..,39
441,Wallis and Futuna Islands,Oceania,Polynesia,Developing regions,0,0,0,0,0,0,...,0,0,0,0,..,..,..,..,..,39
442,Western Sahara,Africa,Northern Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,..,..,..,..,..,39
443,Yemen,Asia,Western Asia,Developing regions,10,0,0,10,20,10,...,20,10,40,40,..,..,..,..,..,39
444,Zambia,Africa,Eastern Africa,Developing regions,150,110,120,180,130,170,...,240,410,410,400,..,..,..,..,..,39
445,Zimbabwe,Africa,Eastern Africa,Developing regions,630,1120,1190,980,640,500,...,1560,1880,2180,2270,..,..,..,..,..,39
446,Unknown,World,World,World,4060,4440,4010,3220,3970,4610,...,1800,2320,18310,4970,..,..,..,..,..,39
447,Total,World,World,World,184290,212690,195200,153570,153530,172550,...,363470,402210,460650,535970,..,..,..,..,..,39

In [50]:
res1 = df1.sort_values(by = ['Total'], ascending = False)
print(res1.head(5))
print(res1.tail(5))

           Country                         AreaName  \
224    Afghanistan                             Asia
225        Albania                           Europe
366  New Caledonia                          Oceania
367    New Zealand                          Oceania
368      Nicaragua  Latin America and the Caribbean

                        Region             DevName   1980   1981   1982  \
224              Southern Asia  Developing regions     10     20     30
225            Southern Europe   Developed regions      0      0      0
366                  Melanesia  Developing regions    160    150    210
367  Australia and New Zealand   Developed regions  34370  34440  23920
368            Central America  Developing regions      0      0      0

      1983   1984   1985  ...   2005   2006   2007   2008  2009  2010  2011  \
224     30     70    100  ...    110    180    140    560    ..    ..    ..
225      0      0      0  ...    130    110    110    140    ..    ..    ..
366    140    130    170  ...    490    450    470    490    ..    ..    ..
367  13620  16900  27070  ...  44680  45550  39120  46960    ..    ..    ..
368     10      0      0  ...     10     20     20     20    ..    ..    ..

     2012  2013  Total
224    ..    ..     39
225    ..    ..     39
366    ..    ..     39
367    ..    ..     39
368    ..    ..     39

[5 rows x 39 columns]
       Country AreaName           Region             DevName    1980    1981  \
302    Germany   Europe   Western Europe   Developed regions    3300    4620
303      Ghana   Africa   Western Africa  Developing regions      60     100
304  Gibraltar   Europe  Southern Europe   Developed regions       0       0
305     Greece   Europe  Southern Europe   Developed regions    4280    5040
447      Total    World            World               World  184290  212690

       1982    1983    1984    1985  ...    2005    2006    2007    2008  \
302    7140    5160    2800    2700  ...    4980    5240    6110    6710
303     110      40      40      50  ...     650     690     670     510
304       0       0       0       0  ...      10       0      10       0
305    3560    3210    4060    4300  ...    1380    1260    1190    1130
447  195200  153570  153530  172550  ...  363470  402210  460650  535970

     2009  2010  2011  2012  2013  Total
302    ..    ..    ..    ..    ..     39
303    ..    ..    ..    ..    ..     39
304    ..    ..    ..    ..    ..     39
305    ..    ..    ..    ..    ..     39
447    ..    ..    ..    ..    ..     39

[5 rows x 39 columns]

In [60]:
#print(df1.Country.is_unique())
print(df1['Country'].is_unique)
print(df1.Country.value_counts())

True
Benin                                             1
Costa Rica                                        1
Belize                                            1
Micronesia (Federated States of)                  1
Slovenia                                          1
Qatar                                             1
Honduras                                          1
Bosnia and Herzegovina                            1
Tajikistan                                        1
Georgia                                           1
Lithuania                                         1
Netherlands                                       1
Canada                                            1
Bulgaria                                          1
Azerbaijan                                        1
Kazakhstan                                        1
Guyana                                            1
Tonga                                             1
Monaco                                            1
Bermuda                                           1
Guinea-Bissau                                     1
Iran (Islamic Republic of)                        1
Lebanon                                           1
Armenia                                           1
United States of America                          1
Unknown                                           1
Gambia                                            1
Nigeria                                           1
Panama                                            1
Eritrea                                           1
                                                 ..
Ukraine                                           1
Lesotho                                           1
Cayman Islands                                    1
Maldives                                          1
Uganda                                            1
Cabo Verde                                        1
Gibraltar                                         1
Kiribati                                          1
Antigua and Barbuda                               1
Grenada                                           1
Kyrgyzstan                                        1
Northern Mariana Islands                          1
Liberia                                           1
Democratic People's Republic of Korea             1
Algeria                                           1
Sierra Leone                                      1
Israel                                            1
Timor-Leste                                       1
Réunion                                           1
Libya                                             1
Yemen                                             1
China, Hong Kong Special Administrative Region    1
Mexico                                            1
Mayotte                                           1
Togo                                              1
Mauritius                                         1
Slovakia                                          1
Saint Helena                                      1
Somalia                                           1
Mali                                              1
Name: Country, Length: 224, dtype: int64

In [61]:
print(df1['AreaName'].is_unique)
print(df1.AreaName.value_counts())

False
Africa                             56
Asia                               51
Latin America and the Caribbean    45
Europe                             43
Oceania                            23
Northern America                    4
World                               2
Name: AreaName, dtype: int64

In [75]:
df1.groupby(['Country','AreaName']).size()

Country                                               AreaName
Afghanistan                                           Asia                               1
Albania                                               Europe                             1
Algeria                                               Africa                             1
American Samoa                                        Oceania                            1
Andorra                                               Europe                             1
Angola                                                Africa                             1
Anguilla                                              Latin America and the Caribbean    1
Antigua and Barbuda                                   Latin America and the Caribbean    1
Argentina                                             Latin America and the Caribbean    1
Armenia                                               Asia                               1
Aruba                                                 Latin America and the Caribbean    1
Australia                                             Oceania                            1
Austria                                               Europe                             1
Azerbaijan                                            Asia                               1
Bahamas                                               Latin America and the Caribbean    1
Bahrain                                               Asia                               1
Bangladesh                                            Asia                               1
Barbados                                              Latin America and the Caribbean    1
Belarus                                               Europe                             1
Belgium                                               Europe                             1
Belize                                                Latin America and the Caribbean    1
Benin                                                 Africa                             1
Bermuda                                               Northern America                   1
Bhutan                                                Asia                               1
Bolivia (Plurinational State of)                      Latin America and the Caribbean    1
Bosnia and Herzegovina                                Europe                             1
Botswana                                              Africa                             1
Brazil                                                Latin America and the Caribbean    1
British Virgin Islands                                Latin America and the Caribbean    1
Brunei Darussalam                                     Asia                               1
                                                                                        ..
The former Yugoslav Republic of Macedonia             Europe                             1
Timor-Leste                                           Asia                               1
Togo                                                  Africa                             1
Tokelau                                               Oceania                            1
Tonga                                                 Oceania                            1
Total                                                 World                              1
Trinidad and Tobago                                   Latin America and the Caribbean    1
Tunisia                                               Africa                             1
Turkey                                                Asia                               1
Turkmenistan                                          Asia                               1
Turks and Caicos Islands                              Latin America and the Caribbean    1
Tuvalu                                                Oceania                            1
Uganda                                                Africa                             1
Ukraine                                               Europe                             1
United Arab Emirates                                  Asia                               1
United Kingdom of Great Britain and Northern Ireland  Europe                             1
United Republic of Tanzania                           Africa                             1
United States Virgin Islands                          Latin America and the Caribbean    1
United States of America                              Northern America                   1
Unknown                                               World                              1
Uruguay                                               Latin America and the Caribbean    1
Uzbekistan                                            Asia                               1
Vanuatu                                               Oceania                            1
Venezuela (Bolivarian Republic of)                    Latin America and the Caribbean    1
Viet Nam                                              Asia                               1
Wallis and Futuna Islands                             Oceania                            1
Western Sahara                                        Africa                             1
Yemen                                                 Asia                               1
Zambia                                                Africa                             1
Zimbabwe                                              Africa                             1
Length: 224, dtype: int64

In [94]:
#b = df1.groupby(by = ['Country'])['Total'].eq(0)

df1.groupby(['Total']).apply(lambda x: len(set(x)) == 0).all()

False

In [95]:
df1.groupby(['Total']).apply(lambda x: len(set(x)) == 0).any()

False